/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module "vue-router/auto-routes" {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from "unplugin-vue-router/types"

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    "index-layout": RouteRecordInfo<"index-layout"la"/"t",
      "/",
      Record<never, never>,
      Re"home"ever, never>
    >"home"om"/""about"er,never "about">,
      ne"/about"erabout: RouteRecordInfo<
      "about">
    >
    "announcement-manage""announcement-manage"   ev"/admin/announcements"announcementmanage": RouteRecordInfo<-"annou"role
      manage"e",-"/admin/"role
      manage"",-"/admin/roles"never,never"system-settings" "runtime-info">,
      Record<never, never>
    >
   ystemsettings    ": R"
      runtimeinfo"<-"/admin/system/status"","user-manage"-"/admin/users"fo
": RouteRecordInfo<""
      "/admin/system/settings",
      files"system/status",     "files"
 or"/files"never
      "runtime-info",
      "user"settings"RouteRecordInfo<
  "settings"m"/settings" "/admin/users",>,
      Record<never, never>
    >
    "playground"er,never
 "playground"-ut"/test"   "404"
      Record<never, never>,
    neverRec "404">
    >
 ev"/:path(.*)"settings: RouteRecordInfo<
      "settings",
      "/se"login","login" er>,
      "/login"playground: RouteRe"docx-preview""playground",   >
    "docx-preview""/preview/docx",never
      "404"pdfpreview"dInfo< "404">
    "pdf-preview"th  "/preview/pdf"
  path: ParamValue<true>
RouteRecordInfo<
      "home",
      "/",
      Rec
Record<never, n>,
      Record<never, never>
    >

outeRecordInfo<
  "system-settings",
"/admin/system/settings"
Record<never, never>,-
Record<never, never
Record<nev

Record<never,"user-manage"
Info<
      "files",
      "/files",
      Record
<n
Record<nev
Record<never, never>
     },
      { path: ParamValue"video-preview"
    login: RouteR"video-preview"  "/preview/video"/login",
      Record<never, never>,
      Record<n"xlsx-preview"   >
    "docx-pre"xlsx-preview"co"/preview/xlsx"docx-preview",
      "/preview/docx",
      Record<never, never>,
      Record<never, never>
    >
    "pdf-preview": RouteRecordInfo<
      "pdf-preview",
      "/preview/pdf",
      Record<never, never>,
      Record<never, never>
    >
    "video-preview": RouteRecordInfo<
      "video-preview",
      "/preview/video",
      Record<never, never>,
      Record<never, never>
    >
    "xlsx-preview": RouteRecordInfo<
      "xlsx-preview",
      "/preview/xlsx",
      Record<never, never>,
      Record<never, never>
    >
  }
}
